[package]
name = "a-hello-world"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Hello World and basic Rust concepts"

[dependencies]
ferris-says.workspace = true